title: Fangjin Yang's Homepage
page-top-title: Fangjin Yang
top-section-bg-text: Data Science & Analytics
home-subtitle: Fangjin Yang&ensp;|&ensp;杨放锦
copyright-text: '&copy; Fangjin Yang 2024-2025. All Rights Reserved.'
